# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a06c8a04a13a623a8f28408a7967d591df62cd01eb579ea28000fcbb0516fd53b94dc7e7460d9826581967b9c71463349cf40ec508c93469e2298d16abbf005e

test:
  secret_key_base: 9535ffb2fda372475b9c2802f08ac1b8f67aee230c6437160c71d88e46c2b8809f103576106605f1678a9bd5a9028f0b9281938dc830aa1453737bf39c756aa4

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
